name: Update github-profile-summary-cards

on:
  create:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: vn7n24fzkq/github-profile-summary-cards@89776cd44fb40c4f7b3e5c2db993728cd700d638 # release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_PROFILE_SUMMARY_CARDS }}
        with:
          USERNAME: ${{ github.repository_owner }}
